name: Setup Python with Poetry
description: "This action sets up Python with Poetry and installs dependencies"

inputs:
  python-version:
    description: "The Python version to use"
    required: false
    default: "3.x"
  cache-key-prefix:
    description: "An optional prefix for the cache key"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.0.0
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Configure Poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./.venv
        key:
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-venv-${{
          inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-venv-${{ inputs.python-version }}-

    - name: Install dependencies
      shell: bash
      run: |
        poetry install --no-interaction --with dev

    - name: Sanity check
      shell: bash
      run: poetry check
