name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        required: false
        default: false
        type: boolean

jobs:
  python-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
      fail-fast: false
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # yamllint disable-line rule:truthy
      DEBUG: ${{ github.event.inputs.debug == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
          cache-key-prefix: "test-env-${{ matrix.python-version }}"

      - name: Extract repo name
        id: extract_repo_name
        run:
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >>
          $GITHUB_ENV

      - name: Run tests
        env:
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          if [ "$DEBUG" = "true" ]; then
            echo "Debug mode enabled"
            set -x
          fi
          poetry run pytest -vvv --cov-branch --cov-report=xml --cov={PACKAGE_NAME}
          ls -lah

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ env.CODECOV_TOKEN }}
